### ISSUE TITLE
Csrpacker

### ISSUE THREAD

**Issue by TAKPJA** [Nitro4CSR/CSRPacker_Nos_Repack#1]

**Comment by Nitro4CSR** [comment]
What is your problem?

**Comment by TAKPJA** [comment]
Can it login iOS' account?

**Comment by Nitro4CSR** [comment]
The packer doesn't log in directly to your account it only de and encrypts the save game files
Totorials on how are on my youtube

**Comment by TAKPJA** [comment]
Ok, thank you
